2024-03-28 21:22:34 ERROR com.jdbccrud.utility.LoggerUtil - Persistence Exception: No result found for query [FROM Person WHERE username=?1] Arguments: newDatabaseTest
2024-03-28 21:40:37 ERROR com.jdbccrud.utility.LoggerUtil - Database Access Exception: Error accessing the database
2024-03-28 21:44:18 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database
2024-03-28 21:47:39 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: No result found for query [FROM Person WHERE username=?1] ERROR: jakarta.persistence.NoResultException: No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:47:39 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database
2024-03-28 21:49:30 ERROR com.jdbccrud.utility.LoggerUtil - General Exception: No result found for query [FROM Person WHERE username=?1] ERROR: jakarta.persistence.NoResultException: No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:49:30 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database
2024-03-28 21:51:30 ERROR com.jdbccrud.utility.LoggerUtil - General Exception: No result found for query [FROM Person WHERE username=?1] ERROR: jakarta.persistence.NoResultException: No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:51:30 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database No result found for query [FROM Person WHERE username=?1] ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:52:09 ERROR com.jdbccrud.utility.LoggerUtil - General Exception: No result found for query [FROM Person WHERE username=?1] ERROR: jakarta.persistence.NoResultException: No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:52:09 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database || No result found for query [FROM Person WHERE username=?1] ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:53:05 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database || No result found for query [FROM Person WHERE username=?1] ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:54:06 ERROR com.jdbccrud.utility.LoggerUtil - DatabaseAccessException: Error accessing the database || No result found for query [FROM Person WHERE username=?1]
2024-03-28 21:55:49 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || No result found for query [FROM Person WHERE username=?1]
2024-03-28 22:00:05 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: newDatabaseTest || No result found for query [FROM Person WHERE username=?1]
2024-03-28 22:10:03 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: Person{id=0, createdDate=2024-03-28T22:10:03.450910, firstName='newDatabaseTest', lastName='newDatabaseTest', lastModifiedDate=2024-03-28T22:10:03.450910, username='null', version=1, items=[]} || not-null property references a null or transient value : com.jdbccrud.person.Person.username
2024-03-28 22:18:27 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: Person{id=0, createdDate=2024-03-28T22:18:27.856101, firstName='newDatabaseTest', lastName='newDatabaseTest', lastModifiedDate=2024-03-28T22:18:27.856101, username='newDatabaseTest', version=0, items=[]} || could not execute statement [ERROR: duplicate key value violates unique constraint "person_username_key"
  Detail: Key (username)=(newDatabaseTest) already exists.] [insert into person (created_date,first_name,last_modified_date,last_name,username,version) values (?,?,?,?,?,?)]
2024-03-28 22:31:17 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: Person{id=0, createdDate=2024-03-28T22:31:17.717766, firstName='newDatabaseTest', lastName='newDatabaseTest', lastModifiedDate=2024-03-28T22:31:17.717766, username='NoVersionTest3', version=0, items=[]} || could not execute statement [ERROR: duplicate key value violates unique constraint "person_username_key"
  Detail: Key (username)=(NoVersionTest3) already exists.] [insert into person (created_date,first_name,last_modified_date,last_name,username,version) values (?,?,?,?,?,?)]
2024-03-28 22:32:52 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: Person{id=0, createdDate=2024-03-28T22:32:51.742548, firstName='newDatabaseTest', lastName='newDatabaseTest', lastModifiedDate=2024-03-28T22:32:51.742548, username='NoVersionTest3', version=5, items=[]} || could not execute statement [ERROR: duplicate key value violates unique constraint "person_username_key"
  Detail: Key (username)=(NoVersionTest3) already exists.] [insert into person (created_date,first_name,last_modified_date,last_name,username,version) values (?,?,?,?,?,?)]
2024-03-28 22:33:02 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: Person{id=0, createdDate=2024-03-28T22:33:02.528057, firstName='newDatabaseTest', lastName='newDatabaseTest', lastModifiedDate=2024-03-28T22:33:02.528057, username='NoVersionTest3', version=5, items=[]} || could not execute statement [ERROR: duplicate key value violates unique constraint "person_username_key"
  Detail: Key (username)=(NoVersionTest3) already exists.] [insert into person (created_date,first_name,last_modified_date,last_name,username,version) values (?,?,?,?,?,?)]
2024-03-28 22:33:35 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: Person{id=0, createdDate=2024-03-28T22:33:35.143120, firstName='newDatabaseTest', lastName='newDatabaseTest', lastModifiedDate=2024-03-28T22:33:35.143120, username='NoVersionTest3', version=5, items=[]} || could not execute statement [ERROR: duplicate key value violates unique constraint "person_username_key"
  Detail: Key (username)=(NoVersionTest3) already exists.] [insert into person (created_date,first_name,last_modified_date,last_name,username,version) values (?,?,?,?,?,?)]
2024-03-28 22:51:45 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: 30 || Error accessing the database || ARGS: 30 ||  this person does not exist in the DB.
2024-03-28 22:54:24 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: 30 ||  this person does not exist in the DB.
2024-03-28 22:55:31 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: 30 ||  this person does not exist in the DB.
2024-03-28 23:08:40 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: NoVersionTest2 || Error accessing the database || ARGS: NoVersionTest2 ||  this person does not exist in the DB.
2024-03-31 15:18:19 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || org.hibernate.query.SemanticException: Could not interpret path expression 'username'
2024-03-31 15:29:31 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || Resource: class com.jdbccrud.tag.Tag || Not Found.
2024-03-31 15:31:29 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || Resource: class com.jdbccrud.tag.Tag || Not Found.
2024-03-31 15:33:41 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.ResourceNotFoundException: Error accessing the database || Resource: class com.jdbccrud.tag.Tag || Not Found.
2024-03-31 15:49:59 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || No result found for query [FROM Tag WHERE name = :tagName]
2024-03-31 15:51:34 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || No result found for query [FROM Tag WHERE name = :tagName]
2024-03-31 15:56:08 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.ResourceNotFoundException: jakarta.persistence.NoResultException: No result found for query [FROM Tag WHERE name = :tagName]
2024-03-31 15:58:21 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || Query did not return a unique result: 2 results were returned
2024-03-31 16:08:49 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: jakarta.persistence.NonUniqueResultException: Query did not return a unique result: 2 results were returned
2024-03-31 16:09:12 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.ResourceNotFoundException: jakarta.persistence.NoResultException: No result found for query [FROM Tag WHERE name = :tagName]
2024-03-31 16:09:43 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.ResourceNotFoundException: jakarta.persistence.NoResultException: No result found for query [FROM Tag WHERE name = :tagName]
2024-03-31 16:11:07 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.ResourceNotFoundException: com.jdbccrud.exception.ResourceNotFoundException: Resource: class com.jdbccrud.tag.Tag || Not Found.
2024-03-31 16:11:24 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.ResourceNotFoundException: com.jdbccrud.exception.ResourceNotFoundException: Resource: class com.jdbccrud.tag.Tag || Not Found.
2024-03-31 20:59:03 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: org.hibernate.exception.ConstraintViolationException: JDBC exception executing SQL [delete from tag where id=?] [ERROR: update or delete on table "tag" violates foreign key constraint "fk_item_tag" on table "item"
  Detail: Key (id)=(1) is still referenced from table "item".] [n/a]
2024-03-31 21:13:52 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: java.lang.IllegalArgumentException: org.hibernate.query.sqm.UnknownPathException: Could not resolve attribute 'tag_id' of 'com.jdbccrud.item.Item' [UPDATE Item i SET i.tag_id = null WHERE i.tag_id = :tagId]
2024-03-31 21:14:50 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: org.hibernate.exception.ConstraintViolationException: JDBC exception executing SQL [delete from tag where id=?] [ERROR: update or delete on table "tag" violates foreign key constraint "fk_item_tag" on table "item"
  Detail: Key (id)=(1) is still referenced from table "item".] [n/a]
2024-03-31 21:18:12 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: org.hibernate.exception.ConstraintViolationException: JDBC exception executing SQL [delete from tag where id=?] [ERROR: update or delete on table "tag" violates foreign key constraint "fk_item_tag" on table "item"
  Detail: Key (id)=(1) is still referenced from table "item".] [n/a]
2024-03-31 21:18:41 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: org.hibernate.exception.ConstraintViolationException: JDBC exception executing SQL [delete from tag where id=?] [ERROR: update or delete on table "tag" violates foreign key constraint "fk_item_tag" on table "item"
  Detail: Key (id)=(1) is still referenced from table "item".] [n/a]
2024-03-31 21:19:15 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: org.hibernate.exception.ConstraintViolationException: JDBC exception executing SQL [delete from tag where id=?] [ERROR: update or delete on table "tag" violates foreign key constraint "fk_item_tag" on table "item"
  Detail: Key (id)=(1) is still referenced from table "item".] [n/a]
2024-03-31 21:19:58 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: org.hibernate.exception.ConstraintViolationException: JDBC exception executing SQL [delete from tag where id=?] [ERROR: update or delete on table "tag" violates foreign key constraint "fk_item_tag" on table "item"
  Detail: Key (id)=(1) is still referenced from table "item".] [n/a]
2024-03-31 21:24:09 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: org.hibernate.exception.ConstraintViolationException: JDBC exception executing SQL [delete from tag where id=?] [ERROR: update or delete on table "tag" violates foreign key constraint "fk_item_tag" on table "item"
  Detail: Key (id)=(5) is still referenced from table "item".] [n/a]
2024-03-31 21:28:37 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: org.hibernate.exception.ConstraintViolationException: JDBC exception executing SQL [delete from tag where id=?] [ERROR: update or delete on table "tag" violates foreign key constraint "fk_item_tag" on table "item"
  Detail: Key (id)=(5) is still referenced from table "item".] [n/a]
2024-03-31 21:32:46 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: org.hibernate.exception.ConstraintViolationException: JDBC exception executing SQL [delete from tag where id=?] [ERROR: update or delete on table "tag" violates foreign key constraint "fk_item_tag" on table "item"
  Detail: Key (id)=(5) is still referenced from table "item".] [n/a]
2024-03-31 21:33:08 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: org.hibernate.exception.ConstraintViolationException: JDBC exception executing SQL [delete from tag where id=?] [ERROR: update or delete on table "tag" violates foreign key constraint "fk_item_tag" on table "item"
  Detail: Key (id)=(5) is still referenced from table "item".] [n/a]
2024-03-31 21:34:47 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: org.hibernate.exception.ConstraintViolationException: JDBC exception executing SQL [delete from tag where id=?] [ERROR: update or delete on table "tag" violates foreign key constraint "fk_item_tag" on table "item"
  Detail: Key (id)=(5) is still referenced from table "item".] [n/a]
2024-04-01 12:56:17 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || ARGS: Tag{id=0, createdDate=null, lastModifiedDate=null, name='null', version=1} ||
2024-04-01 13:01:59 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.ResourceNotFoundException: com.jdbccrud.exception.ResourceNotFoundException: ARGS: 13 ||  this person does not exist in the DB.
2024-04-01 13:08:01 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || org.hibernate.query.sqm.UnknownEntityException: Could not resolve root entity 'item'
2024-04-01 13:08:48 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || org.hibernate.query.sqm.UnknownEntityException: Could not resolve root entity 'item'
2024-04-01 13:09:20 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || org.hibernate.query.sqm.UnknownEntityException: Could not resolve root entity 'item'
2024-04-01 13:14:07 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: Error accessing the database || org.hibernate.query.sqm.UnknownEntityException: Could not resolve root entity 'item'
2024-04-01 13:25:53 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: java.lang.IllegalArgumentException: Argument 'BiggyDB' could not be converted to the identifier type of entity 'com.jdbccrud.person.Person' [Error coercing value]
2024-04-01 13:42:51 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: jakarta.persistence.TransactionRequiredException: No EntityManager with actual transaction available for current thread - cannot reliably process 'persist' call
2024-04-01 13:43:16 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: org.hibernate.PropertyValueException: not-null property references a null or transient value : com.jdbccrud.item.Item.tag
2024-04-01 13:45:30 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: java.lang.IllegalArgumentException: id to load is required for loading
2024-04-01 13:46:35 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: java.lang.IllegalArgumentException: id to load is required for loading
2024-04-01 13:46:59 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: java.lang.IllegalArgumentException: id to load is required for loading
2024-04-01 13:47:13 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: java.lang.IllegalArgumentException: id to load is required for loading
2024-04-01 13:48:03 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: java.lang.IllegalArgumentException: id to load is required for loading
2024-04-01 13:48:10 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: java.lang.IllegalArgumentException: id to load is required for loading
2024-04-01 13:49:06 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: java.lang.IllegalArgumentException: id to load is required for loading
2024-04-01 13:49:27 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: java.lang.IllegalArgumentException: id to load is required for loading
2024-04-01 13:49:53 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: java.lang.IllegalArgumentException: id to load is required for loading
2024-04-01 13:50:17 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: java.lang.IllegalArgumentException: id to load is required for loading
2024-04-01 13:55:48 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: org.hibernate.exception.SQLGrammarException: could not execute statement [ERROR: column "tag_identity" of relation "item" does not exist
  Position: 88] [insert into item (asignee_id,created_date,description,last_modified_date,status,tag_id,tag_identity,version) values (?,?,?,?,?,?,?,?)]
2024-04-01 13:59:57 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: jakarta.persistence.TransactionRequiredException: No EntityManager with actual transaction available for current thread - cannot reliably process 'persist' call
2024-04-01 14:01:02 ERROR com.jdbccrud.utility.LoggerUtil - ERROR: com.jdbccrud.exception.DatabaseAccessException: jakarta.persistence.TransactionRequiredException: No EntityManager with actual transaction available for current thread - cannot reliably process 'persist' call
